### ISSUE TITLE
Invalid session token

### ISSUE THREAD

**Issue by hywax** [hywax/shorter#7]
### Environment

Self-Hosted (Docker)

### Describe the bug

An invalid token for the session is generated each time. 

The problem was described in https://github.com/atinux/nuxt-auth-utils/issues/132

After updating the package, it is necessary to make sure that the variable is not created every time

**Comment by hywax-assistant** [comment]
👋 @hywax
Thanks for opening your first issue here!
We'll try to help you as soon as possible.

 If you like this project, please ⭐ star our repo.
